// Fictional examples that mirror the current pipeline's review categories.
export const demoCases = [
  {
    cell_ref: 'Demo sheet!B12', day: 'Monday', start_time: '09:30', end_time: '10:25',
    department: 'CSE(Data Science)', semester: '3rd', section: 'A',
    subject_raw: 'Soft Skill', subject_code_raw: null, subject_name: null,
    subject_code: null, subject_master_id: null, match_method: 'no_catalog_candidates',
    confidence: 0.49, requires_review: true,
    review_reasons: ['Catalog subject record was not identified unambiguously'],
    scenario_note: 'No subject code was extracted. The department label does not match a stream in the catalog filter.',
  },
  {
    cell_ref: 'Demo sheet!C12', day: 'Monday', start_time: '10:25', end_time: '11:20',
    department: 'CSE', semester: '3rd', section: 'A',
    subject_raw: 'RC-CSE-301', subject_code_raw: 'RC-CSE-301', subject_name: null,
    subject_code: null, subject_master_id: null, match_method: 'unmatched_code',
    confidence: 0.49, requires_review: true,
    review_reasons: ['Catalog subject record was not identified unambiguously'],
    scenario_note: 'A code was extracted, but that exact normalized code does not occur in the saved catalog.',
  },
  {
    cell_ref: 'Demo sheet!K12', day: 'Monday', start_time: '17:00', end_time: '17:30',
    department: 'CSE', semester: '3rd', section: 'A',
    subject_raw: 'Extended Research Hours and College Activity', subject_code_raw: null,
    subject_name: null, subject_code: null, subject_master_id: null,
    match_method: 'non_subject_activity', confidence: 0.49, requires_review: true,
    review_reasons: ['Catalog subject record was not identified unambiguously'],
    scenario_note: 'This is a scheduled activity, so no catalog subject should be assigned.',
  },
  {
    cell_ref: 'Demo sheet!G18', day: 'Tuesday', start_time: '13:40', end_time: '15:20',
    department: 'M.Tech CSE', semester: '3rd', section: 'A',
    subject_raw: 'Project', subject_code_raw: null, subject_name: 'Project – Part 1',
    subject_code: 'PGCSE393', subject_master_id: 1861, match_method: 'semantic',
    cosine_similarity: 0.6891, confidence: 0.672, requires_review: true,
    review_reasons: ['Semantic match needs validation until thresholds are calibrated'],
    match_candidates: [
      { name: 'Project – Part 1', code: 'PGCSE393', score: 0.6891 },
      { name: 'Project Management & Entrepreneurship', code: 'PGCSE301A', score: 0.3729 },
    ],
    scenario_note: 'The name is a semantic suggestion. It is not accepted automatically.',
  },
  {
    cell_ref: 'Demo sheet!G22', day: 'Wednesday', start_time: '13:40', end_time: '15:20',
    department: 'CSE', semester: '3rd', section: 'B',
    subject_raw: 'Analog and digital lab (R-318) Gr-A / Hardware lab Gr-B',
    subject_code_raw: 'ESC-391', subject_name: 'Analog and Digital Electronics',
    subject_code: 'ESC391', subject_master_id: 931, match_method: 'code',
    catalog_course: 'B.Tech', catalog_stream: 'CSE', catalog_semester: '3rd',
    confidence: 1, requires_review: true,
    review_reasons: ['Cell contains multiple subject codes'],
    scenario_note: 'The first code matches, but the cell describes more than one lab or group.',
  },
  {
    cell_ref: 'Demo sheet!C24', day: 'Thursday', start_time: '10:25', end_time: '11:20',
    department: 'CSE', semester: '3rd', section: 'A',
    subject_raw: 'BSC-301', subject_code_raw: 'BSC-301', subject_name: 'Mathematics-III',
    subject_code: 'BSC301', subject_master_id: 929, match_method: 'code',
    catalog_course: 'B.Tech', catalog_stream: 'CSE', catalog_semester: '3rd',
    confidence: 1, requires_review: true,
    review_reasons: ['Time header required AM/PM correction'],
    scenario_note: 'The catalog subject is clear. The timetable header needed a time correction.',
  },
  {
    cell_ref: 'Demo sheet!I28', day: 'Friday', start_time: '15:20', end_time: '16:10',
    department: 'CSE(Data Science)', semester: '3rd', section: 'A',
    subject_raw: 'BSC 301', subject_code_raw: 'BSC 301', subject_name: null,
    subject_code: null, subject_master_id: null, match_method: 'duplicate_code',
    confidence: 0.49, requires_review: true,
    review_reasons: ['Catalog subject record was not identified unambiguously', 'Multiple subjects match'],
    match_candidates: [
      { name: 'Computational Statistics', code: 'BSC301', score: 1 },
      { name: 'Mathematics-III', code: 'BSC301', score: 1 },
    ],
    scenario_note: 'The same code belongs to different catalog subjects. The stream label cannot resolve it.',
  },
  {
    cell_ref: 'Demo sheet!J31', day: 'Friday', start_time: '16:10', end_time: '17:00',
    department: 'CSE(Data Science)', semester: '3rd', section: 'A',
    subject_raw: 'ESCS 201', subject_code_raw: 'ESCS 201',
    subject_name: 'Programming for Problem Solving', subject_code: 'ESCS201',
    subject_master_id: null, match_method: 'duplicate_code', confidence: 0.49,
    requires_review: true,
    review_reasons: ['Catalog subject record was not identified unambiguously', 'Multiple subjects match'],
    scenario_note: 'All matching catalog rows share a name, but no single subject record ID can be chosen.',
  },
  {
    cell_ref: 'Demo sheet!B33', day: 'Saturday', start_time: '09:30', end_time: '10:25',
    department: 'CSE', semester: '7th', section: 'A',
    subject_raw: 'Machine Learning', subject_code_raw: 'PECCS701 E',
    subject_name: 'Machine Learning', subject_code: 'PECCS701E',
    subject_master_id: 945, match_method: 'code',
    catalog_course: 'B.Tech', catalog_stream: 'CSE', catalog_semester: '7th',
    confidence: 1, requires_review: false, review_reasons: [],
    scenario_note: 'The complete code identifies one catalog row and requires no review.',
  },
];

demoCases.push({
  cell_ref: 'Historical example!I7', day: 'Friday', start_time: '15:20', end_time: '16:10',
  department: 'CSE', semester: '7th', section: 'A',
  subject_raw: 'E (Machine Learning', subject_code_raw: 'PECCS701',
  subject_name: 'Machine Learning', subject_code: 'PECCS701E',
  subject_master_id: 945, match_method: 'fuzzy', confidence: 0.88,
  requires_review: true,
  review_reasons: ['Extracted code conflicts with canonical code'],
  scenario_note: 'Historical demonstration only. The current parser reads the full PECCS701 E code and resolves this by code.',
});
